### ISSUE TITLE
Failed to activate the Maya package

### ISSUE THREAD

**Issue by Sosoyan** [davidpaulrosser/atom-maya#10]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [Maya](https://github.com/davidpaulrosser/atom-maya) package, v0.9.0

### Stack Trace

Failed to activate the Maya package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/Sosoyan/.atom/packages/Maya/lib/status-view.coffee:1:1)
  at /Users/Sosoyan/.atom/packages/Maya/lib/status-view.coffee:5:5
  at Object.<anonymous> (/Users/Sosoyan/.atom/packages/Maya/lib/status-view.coffee:77:5)
  at Object.<anonymous> (/Users/Sosoyan/.atom/packages/Maya/lib/status-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/Sosoyan/.atom/packages/Maya/lib/maya.coffee:5:14)
  at Object.<anonymous> (/Users/Sosoyan/.atom/packages/Maya/lib/maya.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:707:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:255:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:234:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:770:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:00.7.0 maya:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "auto-indent",
      "indent-helper"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Maya, v0.9.0
highlight-selected, v0.9.3
monokai, v0.14.0
script, v2.23.0

# Dev
No dev packages
```

**Comment by robbybranham** [comment]
Any work arounds for this yet? Thanks!

**Comment by davidpaulrosser** [comment]
Hi @robbybranham, sorry for the delay. Looking into this now.

**Comment by davidpaulrosser** [comment]
Hi @robbybranham, I've pushed up a new release. Is it working for you?

**Comment by robbybranham** [comment]
Hey, just getting to this. Just tested, everything seems to be functional. Thanks for the update.
