### ISSUE TITLE
Uncaught Error: Can't save buffer with no file path

### ISSUE THREAD

**Issue by lakshbhatnagar** [davidpaulrosser/atom-maya#11]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [Maya](https://github.com/davidpaulrosser/atom-maya) package, v0.17.0

### Stack Trace

Uncaught Error: Can't save buffer with no file path

```
At C:\Users\Laksh-PC\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1008

Error: Can't save buffer with no file path
  at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Laksh-PC\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1008:15)
  at TextBuffer.module.exports.TextBuffer.save (C:\Users\Laksh-PC\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1002:19)
  at TextEditor.module.exports.TextEditor.save (C:\Users\Laksh-PC\AppData\Local\atom\app-1.0.15\resources\app.asar\src\text-editor.js:584:26)
  at Object.module.exports.run (C:\Users\Laksh-PC\.atom\packages\Maya\lib\maya.coffee:47:18)
  at atom-workspace.subscriptions.add.atom.commands.add.maya:run (C:\Users\Laksh-PC\.atom\packages\Maya\lib\maya.coffee:26:80)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Laksh-PC\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:245:29)
  at C:\Users\Laksh-PC\AppData\Local\atom\app-1.0.15\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Laksh-PC\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Laksh-PC\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Laksh-PC\AppData\Local\atom\app-1.0.15\resources\app.asar\src\window-event-handler.js:184:20)

```

### Commands

```
 11x -2:44.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:38.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
 13x -2:32.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:21 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:20.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:20.4.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:18.2.0 core:select-all (atom-text-editor.editor.is-focused)
     -2:17.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:09.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:09.9.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:09.0 core:select-all (atom-text-editor.editor.is-focused)
  8x -2:08.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:05.3.0 grammar-selector:show (atom-text-editor.editor)
     -0:51.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.1.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:03.6.0 maya:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-python"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-modules, v1.1.0
autocomplete-ruby, v0.1.0
language-glsl, v2.0.1
language-hlsl, v1.2.0
language-mel, v0.1.2
Maya, v0.17.0
minimap, v4.13.3

# Dev
No dev packages
```

**Comment by davidpaulrosser** [comment]
Was it working fine for you before the last update?

**Comment by lakshbhatnagar** [comment]
I just downloaded today and try to run but it didn't work for me.

Extra Info = No, i did not use previous update

**Comment by lakshbhatnagar** [comment]
![error](https://cloud.githubusercontent.com/assets/13308696/9985934/dfa87d74-6052-11e5-838d-209730dbd210.JPG)

Every time this error is showed and i don't know why? Please help me!

**Comment by davidpaulrosser** [comment]
I don't use Windows so I'll be more than happy if you could try and fix this and send me a PR?

**Comment by internetimagery** [comment]
Just a quick note that I've also experienced this issue since moving to windows. It also did start happening after the most recent update. (0.17.0)
